# -*- coding: utf-8 -*-
"""milestone_2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Os2RHNXMiwUvCIMJWRxlQfSPoyulHsSx
"""

import random
# Step 1: Using the input function, ask the user to enter a single letter.
user_input = input("Please enter a single letter: ")

# Step 2: Assign the input to a variable called guess.
guess = user_input

# Step 3: Create an if statement that checks if the length of the input is equal to 1 and the input is alphabetical.
if len(guess) == 1 and guess.isalpha():
    # Step 2 (continued): In the body of the if statement, print a message that says "Good guess!".
    print("Good guess!")
else:
    # Step 3 (continued): Create an else block that prints "Oops! That is not a valid input."
    print("Oops! That is not a valid input.")

# Rest of the code remains the same

# Step 1 (continued): Create a list containing the names of your 5 favorite fruits.
favorite_fruits = ["apple", "banana", "orange", "strawberry", "pineapple"]

# Step 2 (continued): Assign the list to a variable called word_list.
word_list = favorite_fruits

# Step 3 (continued): Create the random.choice method and pass the word_list variable into the choice method.
word = random.choice(word_list)

# Step 5: Print out word to the standard output.
print(word)

